config/routes.rb
CompleteNesCollection::Application.routes.draw do
  
  
  get 'developers', to: 'developers#index', as: 'developers'
  get 'developers/:id', to: 'developers#show', as: 'developer'
  
  get 'publishers', to: 'publishers#index', as: 'publishers'
  get 'publishers/:id', to: 'publishers#show', as: 'publisher'
  
  get 'genres', to: 'genres#index', as: 'genres'
  get 'genres/:id', to: 'genres#show', as: 'genre'
  
  get 'games', to: 'games#index', as:'games'  
  get 'games/:id', to: 'games#show', as: 'game'
  
  get 'about_us', to: 'about_us#show', as: 'about_us'
  
  get 'search', to: 'store#search', as: 'search'
  get 'search_results', to: 'store#search_results', as: 'search_results'
  
  get 'sale', to: 'store#sale', as: 'sales'
  get 'new_game', to: 'store#new_game', as: 'new_games'
  
  root 'store#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/about_us.rb
class AboutUs < ActiveRecord::Base
  validates :header, :description, :address, :province, :postal_code, :contact_number, :email, presence: true
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: destroy
  
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :first_name, :last_name, :address, :city, :postal_code, :email, :province_id, presence: true
  belongs_to :province
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  validates :name, presence: true
  has_many :games
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :name, :reg_price, :stock_quantity, :release_year, :developer_id, :genre_id, :publisher_id, presence: true
  validates :reg_price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :stock_quantity, numericality: { only_integer: true }
  belongs_to :genre
  belongs_to :developer
  belongs_to :publisher
  has_many :line_items
  
  mount_uploader :image, GameImageUploader
  
  def self.keyword_search(keywords, genre)
    keywords = "%" + keywords + "%"
    Game.where("(name LIKE ? OR description LIKE ?) AND genre_id = ?", keywords, keywords, genre)
  end
  
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  validates :name, presence: true
  has_many :games
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  validates :quantity, :reg_price, :sale_price, :game_id, :order_id, presence: true
  validates :reg_price, :sale_price, numericality: { greater_than_or_equal_to: 0.01 }
  belongs_to :order
  belongs_to :game
  belongs_to :cart
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :status, :pst_rate, :gst_rate, :hst_rate, :customer_id, presence: true
  validates :pst_rate, :gst_rate, :hst_rate, numericality: { greater_than_or_equal_to: 0.00 }
  belongs_to :customer
  has_many :line_items
end

app/models/province.rb
class Province < ActiveRecord::Base
  validates :name, :pst, :gst, :hst, presence: true
  validates :pst, :gst, :hst, numericality: { greater_than_or_equal_to: 0.00 }
  has_many :customers
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  validates :name, presence: true
  has_many :games
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CompleteNesCollection</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div id="wrapper">
    <%= render 'shared/header' %>
    <br>
    <%= yield %>
  </div>
</body>

</html>

app/views/shared/_header.html.erb
<header>
    <h1 id="company_logo">Complete-Nes Collection</h1>
    <h2 id="logo_heading">For all your Nes Needs</h2>
    <%= form_tag search_results_path, id: 'search', method: 'get' do %>   
        <%= text_field_tag :search_keywords %>
        <%= collection_select params[:genre_selected], :ids, Genre.all, :id, :name, :selected=> :id %>
        <%= submit_tag "Seach" %>
    <% end %>
    <nav id="top_navigation">
        <ul>
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'All Games', games_path %></li>
            <li><%= link_to 'By Genre', genres_path %></li>
            <li><%= link_to 'By Publisher', publishers_path %></li>
            <li><%= link_to 'By Developer', developers_path %></li>
            <li><%= link_to 'Sale', sales_path %></li>
            <li><%= link_to "Recently Added", new_games_path %></li>
            <li><%= link_to 'About Us', about_us_path %></li>
            <li><%= link_to 'Admin Log In', admin_dashboard_path %></li>
        </ul>
    </nav>

</header>