config/routes.rb
CompleteNesCollection::Application.routes.draw do
  
  
  get 'developers', to: 'developers#index', as: 'developers'
  get 'developers/:id', to: 'developers#show', as: 'developer'
  
  get 'publishers', to: 'publishers#index', as: 'publishers'
  get 'publishers/:id', to: 'publishers#show', as: 'publisher'
  
  get 'genres', to: 'genres#index', as: 'genres'
  get 'genres/:id', to: 'genres#show', as: 'genre'
  
  get 'games', to: 'games#index', as:'games'  
  get 'games/:id', to: 'games#show', as: 'game'
  
  get 'about_us', to: 'about_us#show', as: 'about_us'
  
  get 'search', to: 'store#search', as: 'search'
  get 'search_results', to: 'store#search_results', as: 'search_results'
  
  get 'sale', to: 'store#sale', as: 'sales'
  get 'new_game', to: 'store#new_game', as: 'new_games'
  
  root 'store#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/about_us.rb
class AboutUs < ActiveRecord::Base
  validates :header, :description, :address, :province, :postal_code, :contact_number, :email, presence: true
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: destroy
  
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :first_name, :last_name, :address, :city, :postal_code, :email, :province_id, presence: true
  belongs_to :province
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  validates :name, presence: true
  has_many :games
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :name, :reg_price, :stock_quantity, :release_year, :developer_id, :genre_id, :publisher_id, presence: true
  validates :reg_price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :stock_quantity, numericality: { only_integer: true }
  belongs_to :genre
  belongs_to :developer
  belongs_to :publisher
  has_many :line_items
  
  mount_uploader :image, GameImageUploader
  
  def self.keyword_search(keywords, genre)
    keywords = "%" + keywords + "%"
    Game.where("(name LIKE ? OR description LIKE ?) AND genre_id = ?", keywords, keywords, genre)
  end
  
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  validates :name, presence: true
  has_many :games
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  validates :quantity, :reg_price, :sale_price, :game_id, :order_id, presence: true
  validates :reg_price, :sale_price, numericality: { greater_than_or_equal_to: 0.01 }
  belongs_to :order
  belongs_to :game
  belongs_to :cart
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :status, :pst_rate, :gst_rate, :hst_rate, :customer_id, presence: true
  validates :pst_rate, :gst_rate, :hst_rate, numericality: { greater_than_or_equal_to: 0.00 }
  belongs_to :customer
  has_many :line_items
end

app/models/province.rb
class Province < ActiveRecord::Base
  validates :name, :pst, :gst, :hst, presence: true
  validates :pst, :gst, :hst, numericality: { greater_than_or_equal_to: 0.00 }
  has_many :customers
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  validates :name, presence: true
  has_many :games
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    
  end
  
  def show
  end
  
  def create
    
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @games = Game.all
    @new_game = Game.order("id DESC").where("sale_price IS NULL").limit(5)
    @games_on_sale = Game.where("sale_price IS NOT NULL").limit(5)
  end

  def search
  end

  def search_results  
    @found_games = Game.keyword_search(params[:search_keywords], params[:ids]).page(params[:page]).per(5)
  end
  
  def sale
    @games = Game.where("sale_price IS NOT NULL").page(params[:page]).per(5)
  end
  
  def new_game
    @games = Game.order("id DESC").where("sale_price IS NULL").limit(10).page(params[:page]).per(5)
  end
  
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/index.html.erb
<section id="new_games_section">
  <h3>New Games</h3>
  <% @new_game.each do |game| %>
    <div class="new_games">
      <h5><%= link_to game.name, game_path(game) %></h5>
      <%= image_tag game.image_url.to_s, height: '100' %>
    </div>
  <% end %>
</section>

<section id="sale_section">
  <h3>Games On Sale</h3>
  <% @games_on_sale.each do |game| %>
    <div class="games_on_sale">
      <h5><%= link_to game.name, game_path(game) %></h5>
      <%= image_tag game.image_url.to_s, height: '100' %>
    </div>
  <% end %>
</section>

app/views/store/new_game.html.erb
<h3>Recently Added</h3>

<%= paginate @games %>

<% @games.each do |game| %>
  <br>
  <strong><%= link_to game.name, game_path(game) %></strong>
  <br>
  <%= image_tag game.image_url.to_s, height: '150' %>
  <br>
  <p>Regular Price: $<%= game.reg_price %></p>
  <br>
  <hr>
<% end %>

app/views/store/sale.html.erb
<h3>On Sale</h3>

<%= paginate @games %>

<% @games.each do |game| %>
  <br>
  <strong><%= link_to game.name, game_path(game) %></strong>
  <br>
  <%= image_tag game.image_url.to_s, height: '150' %>
  <br>
  <p>Regular Price: $<%= game.reg_price %></p>
  <p>Sale Price: $<%= game.sale_price %></p>
  <br>
  <hr>
<% end %>

  




app/views/store/search.html.erb
<h1>Store#search</h1>
<%= form_tag search_results_path, method: 'get' do %>
  <%= text_field_tag :search_keywords %>
  <%= submit_tag "Seach" %>
<% end %>

app/views/store/search_results.html.erb
<h1>Search results for '<%= params[:search_keywords] %>'</h1>

<%= paginate @found_games %>

<% if @found_games.empty? %>
  <p>No games found.</p>
<% end %>

<%= render partial: 'games/game',
           collection: @found_games %>